# Only needed if you want to preview the site on your own computer.
# GitHub Pages builds the site for you without it.
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "webrick"
